export const CONFIGCONSTANTS = {
  siteName: "Rishvi Hyperview",
  dateFormat: "MM/dd/yyyy hh:mm:ss",
  dateShortFormat: "MM/dd/yyyy",
  momentDateTime24Format: "MM/DD/YYYY hh:mm:ss",
  momentDateTime12Format: "MM/DD/YYYY h:mm A",
  momentTime24Format: "hh:mm:ss",
  momentTime12Format: "hh:mm A",
  momentDateFormat: "MM/DD/YYYY",
  languageOption: true,
  ApiRequestFormat: "MM/DD/YYYY",
  Api24RequestFormat: "YYYY-MM-DD, HH:mm:ss",
  datatableConfig: {
    serverSorting: true,
    serverPaging: true,
    dtMessages: {
      emptyMessage: "No data",
      totalMessage: "Total Records",
    },
    page: {
      pageSize: 10,
      pageNumber: 0,
      totalRecords: 10,
    },
    pageSizeOptions: [10, 25, 50, 100],
    showTotalPagesNumber: 1,
  },
  dataTableIndexColumnWidth: "100",
  imageUpload: {
    ALLOW_FILE_TYPE: ["image/jpeg", "image/jpg", "image/png"],
    MAX_FILE_SIZE: 2,
    MESSAGE: "PLEASE_UPLOAD_VALID_FILE",
    FILE: "jpeg, jpg, png",
  },
  siteLogo: "../../assets/img/logos/RishviHyperviewSide.png",
  siteFavicon: "../../assets/rishvi-favicon.png",
  totalShowMore: 5,
  permissionParentId: "00000000-0000-0000-0000-000000000000",
};
